        <link href="../../css/bootstrap.min.css" rel="stylesheet">
        <link href="../../css/custom.css" rel="stylesheet">
        <link href="../../css/style.default.css" rel="stylesheet" id="theme-stylesheet">
        <link href="../../css/font-awesome.css" rel="stylesheet">
        <link href="../../css/alertify.css" rel="stylesheet">
        <link href="../../css/animate.min.css" rel="stylesheet">
        <link href="../../css/owl.carousel.css" rel="stylesheet">
        <link href="../../css/owl.theme.css" rel="stylesheet">
        <link href="../../css/chosen-custom.css" rel="stylesheet">
        <link href="../../css/chosen.css" rel="stylesheet">
        
    <script type="text/javascript" src="../../js/jquery.js"></script>
    <script type="text/javascript" src="../../js/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="../../js/jquery.maskedinput.js"></script>
    <script type="text/javascript" src="../../js/jquery.cookie.js"></script>
    <script type="text/javascript" src="../../js/respond.min.js"></script>
    <script type="text/javascript" src="../../js/bootstrap.min.js"></script>
    <script type="text/javascript" src="../../js/bootstrap.js"></script>
    <script type="text/javascript" src="../../js/bootstrap-datepicker.js"></script>
    <script type="text/javascript" src="../../js/front.js"></script>
    <script type="text/javascript" src="../../js/tableSpin.js"></script>
    <script type="text/javascript" src="../../js/alertify.js"></script>
    <script type="text/javascript" src="../../js/chosen.jquery.js"></script>
    <script type="text/javascript" src="../../js/waypoints.min.js"></script>
    <script type="text/javascript" src="../../js/sweetalert.js"></script>
    <script type="text/javascript" src="../../js/bootsnipFilterTable.js"></script>
    <script type="text/javascript" src="../../js/modernizr.js"></script>
    <script type="text/javascript" src="../../js/bootstrap-hover-dropdown.js"></script>
    <script type="text/javascript" src="../../js/owl.carousel.min.js"></script>
    <script type="text/javascript" src="../../js/userManegmantConfig.js"></script>